name: 'Mandrill Templates Action'
description: "Update or publish templates to mandrill"
author: "Saurish Kar"

inputs:
  mandrill_key:
    description: "Mandrill api key"
    default: ""

runs:
  using: "node16"
  main: "dist/index.js"